### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by macaienlei** [doseeing/dyws#1]
https://github.com/doseeing/dyws/blob/818b16f3b8a5de1555e8b9e0523567b92f2324a4/src/buffercoder.js#L7

**Comment by macaienlei** [comment]
Error when running npm run test，how to test including webAPI？

**Comment by doseeing** [comment]
https://nodejs.org/api/util.html#util_class_util_textencoder

Version | Changes
v11.0.0 | The class is now available on the global object.
v8.3.0 | Added in: v8.3.0

According this page, `TextDecoder` becomes global since nodejs v11.0.0. My test environment is nodeV13 so test passed. Thanks for your PR.
